---
layout: post
title:  "Welcome to Jekyll!"
date:   2019-04-29 17:40:03 -0500
categories: jekyll update
---

#+title:D3EM Essay
#+Author:Daniel Sauceda
#+Date: 05/24/2018
Five years ago I had no discernible skills in programming, data
science, computation, etc. However, I recognized the potential rewards
in mastering and applying these skills in any field. Over the course
of years, I spent my weekends on learning. After a year, Dr. Arroyave
hired me to explore the possibilities of creating data repositories
for materials science. Although I severely lacked the ability, I
learned great insights into data infrastructures and methods. I could
see the scope of previous work and possibilities moving forward. I
then spent the remainder of undergraduate career pursuing different
technical solutions for solving materials science data problems. The
benefits of this program will take my research to the next "level".

In 1979, VisiCalc was Apple operating systems. It was nothing more
than a simple spreadsheet program (a precursor to excel-like software).
Although VisiCalc didn’t include powerful accounting features, it was
a useful tool for managing accounts, credit card records, taxes and
completing other basic account management tasks. Nevertheless, it had
a massive impact on the accounting/finance community. According to one
of the creators, Dan Bricklin claimed that "VisiCalc took 20 hours of
work for some people and turned it out in 15 minutes and let them
become much more creative,”. While it is a positive note for
accountants, it is also a cautionary tale. The accounting firms that
failed to make the transition found themselves defunct by the early
80s.  We, as scientists and engineers, are on the brink of the next
paradigmal shift.  With the resurgence of Machine Learning, Neural
Networks, AI, etc. combined with more powerful computational
infrastructures, I see that there is a shifting market value of our
skills and research. The D3EM program will enhance my previously
mentioned skill set and make me more competitive in the marketplace.

In June 2011, the Whitehouse published the founding paper for the
Materials Genome Initiative (MGI). The intention of MGI was for the
government to explicitly recognize the importance of accelerated
materials science research for benefiting society. The aftermath has
resulted in numerous organizations and initiatives for generating,
storing, and applying materials science data. With the skills I
already have, I believe that I can be an asset in contributing to the
field and society as a whole in a grand way.

After speaking with many colleagues, it was clear to me that "When
pursuing Ph.D., it was intrinsically essential to choose a research
path that interests you." I have always had an affinity for data and
computation. I feel confident that it is what I want to focus my
efforts. In becoming a graduate student, I need to make my research
mature. I believe that a specializing in Data-Enabled Discovery will
give me the organization skills and knoweledge base to apply my years
of learning towards materials science.

